#!/bin/bash
EXT=$(basename $0) 
case "$1" in
stylesheet)
  ;;
post-process)
  if [ "$VERBOSE" -ge 1 ]
  then
    echo >&2 "Post-process XSL-FO to PDF"
  fi
  fop ${POSTARGS} -fo "${XSLT_PROCESSED}" -"${EXT}" "$OUTPUT_DIR/$(basename ${XSLT_PROCESSED%.*}).${EXT}"
esac
